config/routes.rb
Rails.application.routes.draw do
  resources :genres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'movies#index'

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies 

  # get 'movies' => "movies#index"
  # get 'movies/new' => 'movies#new'
  # get 'movies/:id' => "movies#show", as: 'movie'
  # get 'movies/:id/edit' => 'movies#edit', as: "edit_movie"
  # patch 'movies/:id' => 'movies#update'

  resources :movies do
  resources :reviews
  resources :favorites, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  get 'signin' => "sessions#new"

  resources :users
  get 'signup' => "users#new"
end

app/views/shared/_errors.html.erb
<% if object.errors.any?%>
  <section class="errors">
    <h2>Oops! Your form could not be saved.</h2>

    <h3>
      Plese correct the following:
      <%= pluralize(object.errors.full_messages.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message|%>

        <li><%= message %></li>

      <% end %>
      <li></li>
    </ul>
  </section>


<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
        <div class="flash notice">
          <%= flash[:notice]%>
        </div>
      <% end %>

      <% if flash[:alert]%>
        <div class="flash alert">
          <%= flash[:alert]%>
        </div>
      <% end %>

app/views/shared/_footer.html.erb
<p>
      Copyright &copy <%= Time.now.year%>
      <%= link_to 'The Pragmatic Studio', 'https://online.pragmaticstudio.com' %>
      <%# mady in <a href="https://online.pragmaticstudio.com/">The pragmatic studio</a> %>
      </p>

app/views/shared/_header.html.erb
<header>
    <nav>
      <h1>
      <%= link_to image_tag("logo.png"), root_path%>
    </h1>
      <ul class= "left">
        <li><%= link_to 'Released', movies_path %></li>
        <li><%= link_to 'Upcoming', filtered_movies_path(:upcoming), class: "active" %></li>
        <li><%= link_to 'recent', filtered_movies_path(:recent) %></li>
        <li>
          <%= link_to "Hits", filtered_movies_path(:hits) %>
        </li>
        <li>
          <%= link_to "Flops", filtered_movies_path(:flops) %>
        </li>
        
        <li><%= link_to 'All Users', users_path %></li>

      </ul>
      <ul class="right">
        <% if current_user%>
          <li><%= link_to current_user.name, current_user %> </li>
          <li><%= link_to "Account Settings", edit_user_path(current_user)%></li>
          <li><%= link_to "Sign Out", session_path, data: { turbo_method: :delete}, class: "button"%></li>
        <% else %>
          <li><%= link_to "Sign in", signin_path, class: "button"%></li>
        <li><%= link_to "Sign Up", signup_path, class: "button"%></li>
        <%end %>
      </ul>
    </nav>
    </header>

app/views/shared/_stars.html.erb
<div class="star-rating">
  <div class="back-stars">
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <div class="front-stars" style="width: <%= percent %>%">
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
    </div>
  </div>
</div>